"""
Insight Forge V2 — Memory Architecture Abstractions.

Defines the protocol and basic structures for agent-specific execution memories.
"""

from typing import Any, Protocol, runtime_checkable
from pydantic import BaseModel, Field


@runtime_checkable
class AIMemory(Protocol):
    """Protocol outlining requirements for tracking historical reasoning & execution memory."""

    @property
    def execution_memory(self) -> list[dict[str, Any]]:
        """A timeline list of key-value execution states."""
        ...

    @property
    def reasoning_history(self) -> list[str]:
        """Steps, thought trails, and reflections generated by the agent."""
        ...

    @property
    def rejected_hypotheses(self) -> list[str]:
        """Hypotheses formed that were later falsified by data or validation checks."""
        ...

    @property
    def accepted_findings(self) -> list[str]:
        """Findings validated and verified by data/statistics."""
        ...

    @property
    def evidence_references(self) -> list[str]:
        """Identifiers referencing source data elements backing accepted findings."""
        ...

    def add_reasoning_step(self, step: str) -> None:
        """Append a thought step to history."""
        ...

    def add_hypothesis(self, hypothesis: str, accepted: bool) -> None:
        """Record a hypothesis track and mark whether it was validated/accepted."""
        ...

    def add_finding(self, finding: str) -> None:
        """Log a validated discovery."""
        ...

    def add_evidence_ref(self, ref_id: str) -> None:
        """Register reference link ID pointing to physical evidence validation structures."""
        ...

    def add_execution_record(self, key: str, value: Any) -> None:
        """Record general runtime variable state."""
        ...

    def clear(self) -> None:
        """Reset memory context."""
        ...


class AgentMemory(BaseModel):
    """Standard implementation of the AIMemory protocol using Pydantic."""

    execution_memory: list[dict[str, Any]] = Field(default_factory=list)
    reasoning_history: list[str] = Field(default_factory=list)
    rejected_hypotheses: list[str] = Field(default_factory=list)
    accepted_findings: list[str] = Field(default_factory=list)
    evidence_references: list[str] = Field(default_factory=list)

    def add_reasoning_step(self, step: str) -> None:
        """Append step to memory."""
        self.reasoning_history.append(step)

    def add_hypothesis(self, hypothesis: str, accepted: bool) -> None:
        """Record hypothesis outcome."""
        if accepted:
            self.accepted_findings.append(f"Hypothesis Confirmed: {hypothesis}")
        else:
            self.rejected_hypotheses.append(hypothesis)

    def add_finding(self, finding: str) -> None:
        """Record finding."""
        self.accepted_findings.append(finding)

    def add_evidence_ref(self, ref_id: str) -> None:
        """Append reference ID link."""
        self.evidence_references.append(ref_id)

    def add_execution_record(self, key: str, value: Any) -> None:
        """Store key value variable states."""
        self.execution_memory.append({key: value})

    def clear(self) -> None:
        """Wipe clean."""
        self.execution_memory.clear()
        self.reasoning_history.clear()
        self.rejected_hypotheses.clear()
        self.accepted_findings.clear()
        self.evidence_references.clear()
