"""initial_schema

Revision ID: 9092070a0ca7
Revises: 
Create Date: 2026-07-09 21:12:24.224615
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types.encrypted import EncryptedString
from sqlalchemy.dialects import postgresql


revision: str = '9092070a0ca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_slug', sa.String(length=64), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('tenant_slug', name=op.f('uq_tenants_tenant_slug'))
    )
    op.create_table('cohorts',
    sa.Column('cohort_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cohort_code', sa.String(length=32), nullable=False),
    sa.Column('department_scope', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_cohorts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cohort_id', name=op.f('pk_cohorts'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('corporate_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('assigned_role', sa.String(length=32), nullable=False),
    sa.Column('is_mfa_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('totp_secret', EncryptedString(), nullable=True),
    sa.CheckConstraint("assigned_role IN ('Admin', 'Dean', 'Faculty', 'Student')", name=op.f('ck_users_assigned_role')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('corporate_email', name=op.f('uq_users_corporate_email'))
    )
    op.create_table('coaching_interventions',
    sa.Column('intervention_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('faculty_user_id', sa.UUID(), nullable=False),
    sa.Column('intervention_notes', EncryptedString(), nullable=False),
    sa.Column('recorded_timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_user_id'], ['users.user_id'], name=op.f('fk_coaching_interventions_faculty_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.user_id'], name=op.f('fk_coaching_interventions_student_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_coaching_interventions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('intervention_id', name=op.f('pk_coaching_interventions'))
    )
    op.create_index('ix_coaching_interventions_tenant_student_recorded', 'coaching_interventions', ['recorded_timestamp', 'student_user_id', 'tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jwt_jti', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingress_ip', postgresql.INET(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_sessions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('jwt_jti', name=op.f('uq_sessions_jwt_jti'))
    )
    op.create_table('student_metrics',
    sa.Column('metric_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('raw_average_grade', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('normalized_grade_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('success_indicator_status', sa.String(length=24), nullable=False),
    sa.Column('reporting_period', sa.String(length=32), nullable=False),
    sa.CheckConstraint("success_indicator_status IN ('Safe', 'Amber', 'Critical')", name=op.f('ck_student_metrics_success_indicator_status')),
    sa.CheckConstraint('attendance_percentage >= 0 AND attendance_percentage <= 100.00', name=op.f('ck_student_metrics_attendance_percentage_range')),
    sa.CheckConstraint('raw_average_grade >= 0 AND raw_average_grade <= 100.00', name=op.f('ck_student_metrics_raw_average_grade_range')),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], name=op.f('fk_student_metrics_cohort_id_cohorts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.user_id'], name=op.f('fk_student_metrics_student_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_student_metrics_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('metric_id', name=op.f('pk_student_metrics'))
    )
    op.create_index('ix_student_metrics_tenant_cohort_status', 'student_metrics', ['tenant_id', 'cohort_id', 'success_indicator_status'], unique=False)
    op.create_index('ix_student_metrics_tenant_grade', 'student_metrics', ['tenant_id', sa.literal_column('normalized_grade_score DESC')], unique=False)
    
    # Enable Row Level Security and create tenant isolation policies
    strict_rls_tables = [
        'cohorts',
        'student_metrics',
        'coaching_interventions'
    ]
    for table in strict_rls_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"CREATE POLICY tenant_isolation_policy ON {table} "
            f"USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);"
        )

    permissive_rls_tables = [
        'users',
        'sessions'
    ]
    for table in permissive_rls_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"CREATE POLICY tenant_isolation_policy ON {table} "
            f"USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
            f"OR NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL);"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tenant isolation policies and disable RLS
    tables_with_rls = [
        'users',
        'sessions',
        'cohorts',
        'student_metrics',
        'coaching_interventions'
    ]
    for table in tables_with_rls:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    op.drop_index('ix_student_metrics_tenant_grade', table_name='student_metrics')
    op.drop_index('ix_student_metrics_tenant_cohort_status', table_name='student_metrics')
    op.drop_table('student_metrics')
    op.drop_table('sessions')
    op.drop_index('ix_coaching_interventions_tenant_student_recorded', table_name='coaching_interventions')
    op.drop_table('coaching_interventions')
    op.drop_table('users')
    op.drop_table('cohorts')
    op.drop_table('tenants')
    # ### end Alembic commands ###